# =========================================================
# ORDER SERVICE
# =========================================================

server.port=8082
spring.application.name=ORDER-SERVICE


# =========================================================
# EUREKA
# =========================================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true


# =========================================================
# OTHER SERVICES
# =========================================================

user-service.base-url=http://localhost:8081
payment-service.base-url=http://localhost:8083


# =========================================================
# CONFIG SERVER
# =========================================================

spring.config.import=configserver:http://localhost:8888


# =========================================================
# DATABASE - H2
# =========================================================

spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# H2 CONSOLE
# =========================================================

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# =========================================================
# RESILIENCE4J RETRY
# =========================================================

resilience4j.retry.instances.userService.maxAttempts=3
resilience4j.retry.instances.userService.waitDuration=500ms


# =========================================================
# RESILIENCE4J CIRCUIT BREAKER
# =========================================================

resilience4j.circuitbreaker.instances.userService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.userService.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.userService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.userService.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.userService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.userService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.userService.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.userService.automaticTransitionFromOpenToHalfOpenEnabled=true


# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always