spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webmvc:
          routes:

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users
              filters:
                - SetPath=/api/users

            - id: user-service-id
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/(?<segment>.*), /api/users/${segment}

            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/orders/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true